#!/usr/bin/env bash
###############################################################################
# DiaBay - Professional Slide & Film Digitization System Installer
#
# Automated installation script for Linux. Installs dependencies,
# configures directories, builds frontend, and sets up the application.
#
# Author: korgraph.io
# Requires: Python 3.10+, Node.js 18+ (optional, for building)
###############################################################################

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# ============================================================================
# HELPERS
# ============================================================================

print_header() {
    echo -e "\n${CYAN}========================================${NC}"
    echo -e "${CYAN} $1${NC}"
    echo -e "${CYAN}========================================${NC}\n"
}

print_success() {
    echo -e "${GREEN}[OK]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_info() {
    echo -e "${YELLOW}[INFO]${NC} $1"
}

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# ============================================================================
# MAIN INSTALLATION
# ============================================================================

print_header "DiaBay Installer for Linux"
echo -e "Professional Slide & Film Digitization System\n"

# Get script directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BACKEND_DIR="$SCRIPT_DIR/backend"

# ============================================================================
# DEPENDENCY CHECKS
# ============================================================================

print_header "Checking Dependencies"

# Check Python
if command_exists python3; then
    PYTHON_VERSION=$(python3 --version | cut -d' ' -f2)
    print_success "Python $PYTHON_VERSION found"
    PYTHON_CMD="python3"
elif command_exists python; then
    PYTHON_VERSION=$(python --version | cut -d' ' -f2)
    print_success "Python $PYTHON_VERSION found"
    PYTHON_CMD="python"
else
    print_error "Python 3.10+ not found"
    echo -e "${YELLOW}Please install Python: sudo apt install python3 python3-venv python3-pip${NC}"
    exit 1
fi

# Check Node.js (optional)
HAS_NODE=false
if command_exists node; then
    NODE_VERSION=$(node --version | sed 's/v//')
    print_success "Node.js $NODE_VERSION found"
    HAS_NODE=true
else
    print_info "Node.js not found - will use pre-built frontend from CI/CD"
fi

# ============================================================================
# DIRECTORY CONFIGURATION
# ============================================================================

print_header "Directory Configuration"

# Get user directories
USER_DOCUMENTS="${HOME}/Documents"
USER_PICTURES="${HOME}/Pictures"

# Prompt for input directory
echo -e "${YELLOW}Input directory (where scanner saves TIFF files):${NC}"
read -p "  Path [$USER_DOCUMENTS]: " INPUT_DIR
INPUT_DIR="${INPUT_DIR:-$USER_DOCUMENTS}"
INPUT_DIR=$(realpath -m "$INPUT_DIR")
print_success "Input: $INPUT_DIR"

# Prompt for output directory
echo -e "\n${YELLOW}Output directory (where enhanced images will be saved):${NC}"
read -p "  Path [$USER_PICTURES/dias]: " OUTPUT_DIR
OUTPUT_DIR="${OUTPUT_DIR:-$USER_PICTURES/dias}"
OUTPUT_DIR=$(realpath -m "$OUTPUT_DIR")
print_success "Output: $OUTPUT_DIR"

# Derive other directories
ANALYSED_DIR="$(dirname "$INPUT_DIR")/analysed"
MODELS_DIR="$BACKEND_DIR/models"

print_info "Analysed: $ANALYSED_DIR (auto-derived)"
print_info "Models: $MODELS_DIR (auto-derived)"

# Create directories
echo -e "\n${YELLOW}Creating directories...${NC}"
for dir in "$INPUT_DIR" "$ANALYSED_DIR" "$OUTPUT_DIR" "$MODELS_DIR"; do
    if [ ! -d "$dir" ]; then
        mkdir -p "$dir"
        print_success "Created: $dir"
    else
        print_info "Exists: $dir"
    fi
done

# ============================================================================
# CREATE .ENV FILE
# ============================================================================

print_header "Creating Configuration"

ENV_PATH="$BACKEND_DIR/.env"
cat > "$ENV_PATH" << EOF
# DiaBay Configuration
# Generated by install.sh on $(date '+%Y-%m-%d %H:%M:%S')

# Directories
INPUT_DIR=$INPUT_DIR
ANALYSED_DIR=$ANALYSED_DIR
OUTPUT_DIR=$OUTPUT_DIR
MODELS_DIR=$MODELS_DIR

# Image Processing
JPEG_QUALITY=95
CLAHE_CLIP_LIMIT=1.5
HISTOGRAM_CLIP=0.5
ENABLE_FACE_DETECTION=true
ADAPTIVE_CLAHE_GRID=true

# Output Formats
ENABLE_JPEG_XL=false
ENABLE_PNG_ARCHIVE=false
ENABLE_TIFF_ARCHIVE=false

# Duplicate Detection
DUPLICATE_THRESHOLD=0.95
AUTO_SKIP_DUPLICATES=true

# Server
HOST=0.0.0.0
PORT=8000
RELOAD=false

# Database
DATABASE_URL=sqlite+aiosqlite:///$BACKEND_DIR/diabay.db
EOF

print_success "Created: $ENV_PATH"

# ============================================================================
# PYTHON ENVIRONMENT SETUP
# ============================================================================

print_header "Setting Up Python Environment"

VENV_DIR="$BACKEND_DIR/.venv"

# Create virtual environment
if [ ! -d "$VENV_DIR" ]; then
    echo -e "${YELLOW}Creating virtual environment...${NC}"
    $PYTHON_CMD -m venv "$VENV_DIR"
    print_success "Virtual environment created"
else
    print_info "Virtual environment exists"
fi

# Activate virtual environment
source "$VENV_DIR/bin/activate"

# Upgrade pip
echo -e "${YELLOW}Upgrading pip...${NC}"
pip install --upgrade pip --quiet

# Install PyTorch (CPU-only for better compatibility)
echo -e "${YELLOW}Installing PyTorch (CPU-only)...${NC}"
pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu --quiet
print_success "PyTorch installed"

# Install requirements
echo -e "${YELLOW}Installing dependencies...${NC}"
pip install -r "$BACKEND_DIR/requirements.txt" --quiet
print_success "All dependencies installed"

# ============================================================================
# FRONTEND BUILD
# ============================================================================

print_header "Frontend Setup"

FRONTEND_DIR="$SCRIPT_DIR/frontend"
DIST_DIR="$FRONTEND_DIR/dist"

if [ "$HAS_NODE" = true ]; then
    echo -e "${YELLOW}Building frontend from source...${NC}"
    cd "$FRONTEND_DIR"

    # Install dependencies
    echo -e "${YELLOW}Installing Node.js dependencies...${NC}"
    npm install --silent 2>&1 >/dev/null
    print_success "Dependencies installed"

    # Build frontend
    echo -e "${YELLOW}Building production bundle...${NC}"
    npm run build 2>&1 >/dev/null
    print_success "Frontend built successfully"

    cd "$SCRIPT_DIR"
elif [ -d "$DIST_DIR" ]; then
    print_success "Using pre-built frontend from CI/CD"
else
    print_error "No frontend build found and Node.js not available"
    echo -e "${YELLOW}Options:${NC}"
    echo -e "${YELLOW}  1. Install Node.js and re-run this script${NC}"
    echo -e "${YELLOW}  2. Download pre-built frontend from CI/CD artifacts${NC}"
fi

# ============================================================================
# CREATE STARTUP SCRIPT
# ============================================================================

print_header "Creating Startup Scripts"

START_SCRIPT_PATH="$SCRIPT_DIR/start-diabay.sh"
cat > "$START_SCRIPT_PATH" << 'EOF'
#!/usr/bin/env bash
###############################################################################
# DiaBay Startup Script
# Generated by install.sh
###############################################################################

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BACKEND_DIR="$SCRIPT_DIR/backend"

echo -e "\033[0;36mStarting DiaBay...\033[0m"

# Activate virtual environment
source "$BACKEND_DIR/.venv/bin/activate"

# Change to backend directory
cd "$BACKEND_DIR"

# Start server
echo -e "\033[0;32mServer starting on http://localhost:8000\033[0m"
echo -e "\033[1;33mPress Ctrl+C to stop\n\033[0m"

python main.py
EOF

chmod +x "$START_SCRIPT_PATH"
print_success "Created: $START_SCRIPT_PATH"

# ============================================================================
# CREATE SYSTEMD SERVICE (OPTIONAL)
# ============================================================================

print_header "Systemd Service Setup"

echo -e "${YELLOW}Create systemd service for auto-start? (y/N):${NC}"
read -p "  " CREATE_SERVICE
if [[ "$CREATE_SERVICE" =~ ^[Yy]$ ]]; then
    SERVICE_PATH="$HOME/.config/systemd/user/diabay.service"
    mkdir -p "$HOME/.config/systemd/user"

    cat > "$SERVICE_PATH" << EOF
[Unit]
Description=DiaBay - Professional Slide Digitization System
After=network.target

[Service]
Type=simple
WorkingDirectory=$BACKEND_DIR
ExecStart=$VENV_DIR/bin/python $BACKEND_DIR/main.py
Restart=on-failure
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=default.target
EOF

    print_success "Created: $SERVICE_PATH"

    # Reload systemd and enable service
    systemctl --user daemon-reload
    systemctl --user enable diabay.service
    print_success "Service enabled"

    echo -e "\n${YELLOW}Service commands:${NC}"
    echo -e "  Start:   ${GREEN}systemctl --user start diabay${NC}"
    echo -e "  Stop:    ${GREEN}systemctl --user stop diabay${NC}"
    echo -e "  Status:  ${GREEN}systemctl --user status diabay${NC}"
    echo -e "  Logs:    ${GREEN}journalctl --user -u diabay -f${NC}"
fi

# ============================================================================
# INSTALLATION COMPLETE
# ============================================================================

print_header "Installation Complete!"

echo -e "${GREEN}Configuration:${NC}"
echo -e "  Input:    $INPUT_DIR"
echo -e "  Output:   $OUTPUT_DIR"
echo -e "  Analysed: $ANALYSED_DIR"

echo -e "\n${YELLOW}To start DiaBay:${NC}"
echo -e "  ${GREEN}./start-diabay.sh${NC}"

echo -e "\n${CYAN}Then open: http://localhost:8000${NC}"

echo -e "\n${CYAN}========================================${NC}"
echo -e "${CYAN}Happy scanning! https://korgraph.io${NC}"
echo -e "${CYAN}========================================${NC}\n"
