#!/usr/bin/env pwsh
<#
.SYNOPSIS
    DiaBay - Professional Slide & Film Digitization System Installer
.DESCRIPTION
    Automated installation script for Windows. Installs dependencies,
    configures directories, builds frontend, and sets up the application.
.NOTES
    Author: korgraph.io
    Requires: Python 3.10+, Node.js 18+ (for building)
#>

[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"

# ============================================================================
# HELPERS
# ============================================================================

function Write-Header {
    param([string]$Text)
    Write-Host "`n========================================" -ForegroundColor Cyan
    Write-Host " $Text" -ForegroundColor Cyan
    Write-Host "========================================`n" -ForegroundColor Cyan
}

function Write-Success {
    param([string]$Text)
    Write-Host "[OK]" -ForegroundColor Green -NoNewline
    Write-Host " $Text"
}

function Write-Error {
    param([string]$Text)
    Write-Host "[ERROR]" -ForegroundColor Red -NoNewline
    Write-Host " $Text"
}

function Write-Info {
    param([string]$Text)
    Write-Host "[INFO]" -ForegroundColor Yellow -NoNewline
    Write-Host " $Text"
}

function Test-Command {
    param([string]$Command)
    $null = Get-Command $Command -ErrorAction SilentlyContinue
    return $?
}

# ============================================================================
# MAIN INSTALLATION
# ============================================================================

Write-Header "DiaBay Installer for Windows"
Write-Host "Professional Slide & Film Digitization System`n" -ForegroundColor White

# Get script directory
$SCRIPT_DIR = $PSScriptRoot
$BACKEND_DIR = Join-Path $SCRIPT_DIR "backend"

# ============================================================================
# DEPENDENCY CHECKS
# ============================================================================

Write-Header "Checking Dependencies"

# Check Python
if (Test-Command "python") {
    $pythonVersion = (python --version 2>&1) -replace "Python ", ""
    Write-Success "Python $pythonVersion found"
} else {
    Write-Error "Python 3.10+ not found"
    Write-Host "Please install Python from https://www.python.org/downloads/" -ForegroundColor Yellow
    exit 1
}

# Check Node.js (optional, only for building)
$hasNode = Test-Command "node"
if ($hasNode) {
    $nodeVersion = (node --version 2>&1) -replace "v", ""
    Write-Success "Node.js $nodeVersion found"
} else {
    Write-Info "Node.js not found - will use pre-built frontend from CI/CD"
}

# ============================================================================
# DIRECTORY CONFIGURATION
# ============================================================================

Write-Header "Directory Configuration"

# Get user directories
$userDocuments = [Environment]::GetFolderPath("MyDocuments")
$userPictures = [Environment]::GetFolderPath("MyPictures")

# Prompt for input directory
Write-Host "Input directory (where scanner saves TIFF files):" -ForegroundColor Yellow
$defaultInput = $userDocuments
$inputDir = Read-Host "  Path [$defaultInput]"
if ([string]::IsNullOrWhiteSpace($inputDir)) {
    $inputDir = $defaultInput
}
$inputDir = [System.IO.Path]::GetFullPath($inputDir)
Write-Success "Input: $inputDir"

# Prompt for output directory
Write-Host "`nOutput directory (where enhanced images will be saved):" -ForegroundColor Yellow
$defaultOutput = Join-Path $userPictures "dias"
$outputDir = Read-Host "  Path [$defaultOutput]"
if ([string]::IsNullOrWhiteSpace($outputDir)) {
    $outputDir = $defaultOutput
}
$outputDir = [System.IO.Path]::GetFullPath($outputDir)
Write-Success "Output: $outputDir"

# Derive other directories
$analysedDir = Join-Path (Split-Path $inputDir -Parent) "analysed"
$modelsDir = Join-Path $BACKEND_DIR "models"

Write-Info "Analysed: $analysedDir (auto-derived)"
Write-Info "Models: $modelsDir (auto-derived)"

# Create directories
Write-Host "`nCreating directories..." -ForegroundColor Yellow
foreach ($dir in @($inputDir, $analysedDir, $outputDir, $modelsDir)) {
    if (!(Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
        Write-Success "Created: $dir"
    } else {
        Write-Info "Exists: $dir"
    }
}

# ============================================================================
# CREATE .ENV FILE
# ============================================================================

Write-Header "Creating Configuration"

$envPath = Join-Path $BACKEND_DIR ".env"
$envContent = @"
# DiaBay Configuration
# Generated by install.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

# Directories
INPUT_DIR=$($inputDir -replace '\\', '/')
ANALYSED_DIR=$($analysedDir -replace '\\', '/')
OUTPUT_DIR=$($outputDir -replace '\\', '/')
MODELS_DIR=$($modelsDir -replace '\\', '/')

# Image Processing
JPEG_QUALITY=95
CLAHE_CLIP_LIMIT=1.5
HISTOGRAM_CLIP=0.5
ENABLE_FACE_DETECTION=true
ADAPTIVE_CLAHE_GRID=true

# Output Formats
ENABLE_JPEG_XL=false
ENABLE_PNG_ARCHIVE=false
ENABLE_TIFF_ARCHIVE=false

# Duplicate Detection
DUPLICATE_THRESHOLD=0.95
AUTO_SKIP_DUPLICATES=true

# Server
HOST=0.0.0.0
PORT=8000
RELOAD=false

# Database
DATABASE_URL=sqlite+aiosqlite:///$($BACKEND_DIR -replace '\\', '/')/diabay.db
"@

$envContent | Out-File -FilePath $envPath -Encoding utf8 -NoNewline
Write-Success "Created: $envPath"

# ============================================================================
# PYTHON ENVIRONMENT SETUP
# ============================================================================

Write-Header "Setting Up Python Environment"

$venvDir = Join-Path $BACKEND_DIR ".venv"

# Create virtual environment
if (!(Test-Path $venvDir)) {
    Write-Host "Creating virtual environment..." -ForegroundColor Yellow
    python -m venv $venvDir
    Write-Success "Virtual environment created"
} else {
    Write-Info "Virtual environment exists"
}

# Activate virtual environment
$activateScript = Join-Path $venvDir "Scripts\Activate.ps1"
Write-Host "Activating virtual environment..." -ForegroundColor Yellow
& $activateScript

# Upgrade pip
Write-Host "Upgrading pip..." -ForegroundColor Yellow
python -m pip install --upgrade pip --quiet

# Install PyTorch (CPU-only for better compatibility)
Write-Host "Installing PyTorch (CPU-only)..." -ForegroundColor Yellow
pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu --quiet
Write-Success "PyTorch installed"

# Install requirements
Write-Host "Installing dependencies..." -ForegroundColor Yellow
$requirementsPath = Join-Path $BACKEND_DIR "requirements.txt"
pip install -r $requirementsPath --quiet
Write-Success "All dependencies installed"

# ============================================================================
# FRONTEND BUILD
# ============================================================================

Write-Header "Frontend Setup"

$frontendDir = Join-Path $SCRIPT_DIR "frontend"
$distDir = Join-Path $frontendDir "dist"

if ($hasNode) {
    Write-Host "Building frontend from source..." -ForegroundColor Yellow
    Push-Location $frontendDir

    # Install dependencies
    Write-Host "Installing Node.js dependencies..." -ForegroundColor Yellow
    npm install --silent 2>&1 | Out-Null
    Write-Success "Dependencies installed"

    # Build frontend
    Write-Host "Building production bundle..." -ForegroundColor Yellow
    npm run build 2>&1 | Out-Null
    Write-Success "Frontend built successfully"

    Pop-Location
} elseif (Test-Path $distDir) {
    Write-Success "Using pre-built frontend from CI/CD"
} else {
    Write-Error "No frontend build found and Node.js not available"
    Write-Host "Options:" -ForegroundColor Yellow
    Write-Host "  1. Install Node.js and re-run this script" -ForegroundColor Yellow
    Write-Host "  2. Download pre-built frontend from CI/CD artifacts" -ForegroundColor Yellow
}

# ============================================================================
# CREATE STARTUP SCRIPT
# ============================================================================

Write-Header "Creating Startup Scripts"

$startScriptPath = Join-Path $SCRIPT_DIR "start-diabay.ps1"
$startScriptContent = @"
#!/usr/bin/env pwsh
# DiaBay Startup Script
# Generated by install.ps1

`$ErrorActionPreference = "Stop"
`$BACKEND_DIR = Join-Path `$PSScriptRoot "backend"

Write-Host "Starting DiaBay..." -ForegroundColor Cyan

# Activate virtual environment
`$activateScript = Join-Path `$BACKEND_DIR ".venv\Scripts\Activate.ps1"
& `$activateScript

# Change to backend directory
Push-Location `$BACKEND_DIR

# Start server
Write-Host "Server starting on http://localhost:8000" -ForegroundColor Green
Write-Host "Press Ctrl+C to stop`n" -ForegroundColor Yellow

python main.py

Pop-Location
"@

$startScriptContent | Out-File -FilePath $startScriptPath -Encoding utf8 -NoNewline
Write-Success "Created: $startScriptPath"

# Create batch file wrapper
$batchPath = Join-Path $SCRIPT_DIR "start-diabay.bat"
$batchContent = @"
@echo off
powershell -ExecutionPolicy Bypass -File "%~dp0start-diabay.ps1"
"@

$batchContent | Out-File -FilePath $batchPath -Encoding ascii -NoNewline
Write-Success "Created: $batchPath"

# ============================================================================
# INSTALLATION COMPLETE
# ============================================================================

Write-Header "Installation Complete!"

Write-Host "Configuration:" -ForegroundColor Green
Write-Host "  Input:    $inputDir" -ForegroundColor White
Write-Host "  Output:   $outputDir" -ForegroundColor White
Write-Host "  Analysed: $analysedDir" -ForegroundColor White

Write-Host "`nTo start DiaBay:" -ForegroundColor Yellow
Write-Host "  .\start-diabay.bat" -ForegroundColor White
Write-Host "  or" -ForegroundColor Gray
Write-Host "  .\start-diabay.ps1" -ForegroundColor White

Write-Host "`nThen open: http://localhost:8000" -ForegroundColor Cyan

Write-Host "`nOptional - Create Desktop Shortcut:" -ForegroundColor Yellow
$createShortcut = Read-Host "Create desktop shortcut? (y/N)"
if ($createShortcut -eq "y" -or $createShortcut -eq "Y") {
    $WshShell = New-Object -ComObject WScript.Shell
    $Desktop = [Environment]::GetFolderPath("Desktop")
    $ShortcutPath = Join-Path $Desktop "DiaBay.lnk"
    $Shortcut = $WshShell.CreateShortcut($ShortcutPath)
    $Shortcut.TargetPath = "powershell.exe"
    $Shortcut.Arguments = "-ExecutionPolicy Bypass -File `"$startScriptPath`""
    $Shortcut.WorkingDirectory = $SCRIPT_DIR
    $Shortcut.Description = "DiaBay - Professional Slide Digitization System"
    $Shortcut.Save()
    Write-Success "Desktop shortcut created"
}

Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "Happy scanning! " -ForegroundColor White -NoNewline
Write-Host "https://korgraph.io" -ForegroundColor Cyan
Write-Host "========================================`n" -ForegroundColor Cyan
